### ISSUE TITLE
variables description

### ISSUE THREAD

**Issue by rogelioamancisidor** [nateGeorge/preprocess_lending_club_data#1]
By any chance do you have the excel files with variable descriptions? I cannot find the files and I remember that there are two files out there, one for the accepted loans and another for the rejected ones, with variable descriptions.

**Comment by nateGeorge** [comment]
Looks like it's available to download from LC still: https://www.kaggle.com/wordsforthewise/lending-club/discussion/170691

We should probably add it to this repo and/or kaggle before they take it down though.
