### ISSUE TITLE
do you know how to get all data till today?

### ISSUE THREAD

**Issue by Sandy4321** [nateGeorge/preprocess_lending_club_data#2]
do you know how to get all data till today?

**Comment by nateGeorge** [comment]
Last I checked (over a year ago) you could fetch details on specific loans based on their IDs, but I think they took down the bulk data downloads.

**Comment by Sandy4321** [comment]
Can you share data then

**Comment by nateGeorge** [comment]
No, sorry. I don't have any more data.
